//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Portfolio.ResourceFiles.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All posts.
        /// </summary>
        public static string AllPosts {
            get {
                return ResourceManager.GetString("AllPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tales of Brevis: A Beast Called God.
        /// </summary>
        public static string Brevis {
            get {
                return ResourceManager.GetString("Brevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local 2-player asymmetric multiplayer game where one player collects carrots while the other tries to stop them..
        /// </summary>
        public static string BrevisDescription {
            get {
                return ResourceManager.GetString("BrevisDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy me a beer.
        /// </summary>
        public static string BuyMeABeer {
            get {
                return ResourceManager.GetString("BuyMeABeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I couldn&apos;t find that post :(.
        /// </summary>
        public static string CouldntFindPost {
            get {
                return ResourceManager.GetString("CouldntFindPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English (Native).
        /// </summary>
        public static string EnglishNative {
            get {
                return ResourceManager.GetString("EnglishNative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hog Wild.
        /// </summary>
        public static string HogWild {
            get {
                return ResourceManager.GetString("HogWild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herd the pigs into their pens, but make sure they don&apos;t fall into the black holes..
        /// </summary>
        public static string HogWildDescription {
            get {
                return ResourceManager.GetString("HogWildDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosted on Azure.
        /// </summary>
        public static string HostedOnAzure {
            get {
                return ResourceManager.GetString("HostedOnAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to my portfolio!.
        /// </summary>
        public static string Intro1 {
            get {
                return ResourceManager.GetString("Intro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is where I show the games I&apos;ve made, skills I&apos;ve learned, and blog posts I&apos;ve written..
        /// </summary>
        public static string Intro2 {
            get {
                return ResourceManager.GetString("Intro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I made this website using Blazor as a challenge to myself to learn web development..
        /// </summary>
        public static string Intro3 {
            get {
                return ResourceManager.GetString("Intro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (JLPT N3).
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Developer, Programmer, Technical Writer.
        /// </summary>
        public static string JobTitles {
            get {
                return ResourceManager.GetString("JobTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lark.
        /// </summary>
        public static string Lark {
            get {
                return ResourceManager.GetString("Lark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag your finger or mouse up and down the screen to catch notes in time to the music in this rhythm game about anxiety..
        /// </summary>
        public static string LarkDescription {
            get {
                return ResourceManager.GetString("LarkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; 1 year.
        /// </summary>
        public static string LessThanOneYear {
            get {
                return ResourceManager.GetString("LessThanOneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn.
        /// </summary>
        public static string LinkedIn {
            get {
                return ResourceManager.GetString("LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made with Blazor.
        /// </summary>
        public static string MadeWith {
            get {
                return ResourceManager.GetString("MadeWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliot Cowley.
        /// </summary>
        public static string MyName {
            get {
                return ResourceManager.GetString("MyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, no blog posts yet :(.
        /// </summary>
        public static string NoBlogPosts {
            get {
                return ResourceManager.GetString("NoBlogPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found :(.
        /// </summary>
        public static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - 3 years.
        /// </summary>
        public static string OneToThreeYears {
            get {
                return ResourceManager.GetString("OneToThreeYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt; 3 years.
        /// </summary>
        public static string OverThreeYears {
            get {
                return ResourceManager.GetString("OverThreeYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play on itch.io.
        /// </summary>
        public static string PlayOnItch {
            get {
                return ResourceManager.GetString("PlayOnItch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play on Windows / Xbox.
        /// </summary>
        public static string PlayWindowsXbox {
            get {
                return ResourceManager.GetString("PlayWindowsXbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following video shows a few of the games that I&apos;ve worked on..
        /// </summary>
        public static string Projects1 {
            get {
                return ResourceManager.GetString("Projects1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below are some of the projects I&apos;ve worked on, with links to play them and view source code..
        /// </summary>
        public static string Projects2 {
            get {
                return ResourceManager.GetString("Projects2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest.
        /// </summary>
        public static string Quest {
            get {
                return ResourceManager.GetString("Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control two characters with unique abilities and move between paths to collect coins and defeat enemies in this rhythm-based auto-runner..
        /// </summary>
        public static string QuestDescription {
            get {
                return ResourceManager.GetString("QuestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results for.
        /// </summary>
        public static string SearchResults1 {
            get {
                return ResourceManager.GetString("SearchResults1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string SearchResults2 {
            get {
                return ResourceManager.GetString("SearchResults2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here are the skills I&apos;ve learned, organized by how many years of experience I have with them..
        /// </summary>
        public static string Skills1 {
            get {
                return ResourceManager.GetString("Skills1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For my full resume, including educational and work history, see my.
        /// </summary>
        public static string Skills2 {
            get {
                return ResourceManager.GetString("Skills2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        public static string Skills3 {
            get {
                return ResourceManager.GetString("Skills3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string SkillsHeader {
            get {
                return ResourceManager.GetString("SkillsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical Writing.
        /// </summary>
        public static string TechnicalWriting {
            get {
                return ResourceManager.GetString("TechnicalWriting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gather gerbils to fight enemies and solve puzzles in this 3D physics action game..
        /// </summary>
        public static string UggDescription {
            get {
                return ResourceManager.GetString("UggDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View code on GitHub.
        /// </summary>
        public static string ViewCodeOnGitHub {
            get {
                return ResourceManager.GetString("ViewCodeOnGitHub", resourceCulture);
            }
        }
    }
}
